export const EVM_CHAINS = [
  {
    id: "ethereum",
    label: "Ethereum",
    kind: "evm",
    chainName: "eth-mainnet",
    nativeSymbol: "ETH",
    decimals: 18,
    explorerUrl: "https://etherscan.io/tx/",
    rpcUrls: ["https://cloudflare-eth.com"],
    keywords: ["ethereum", "eth", "etherscan", "erc20", "mainnet"],
  },
  {
    id: "bsc",
    label: "BNB Smart Chain",
    kind: "evm",
    chainName: "bsc-mainnet",
    nativeSymbol: "BNB",
    decimals: 18,
    explorerUrl: "https://bscscan.com/tx/",
    rpcUrls: ["https://bsc-dataseed.binance.org/"],
    keywords: ["bsc", "binance", "bscscan", "bep20", "bnb"],
  },
  {
    id: "polygon",
    label: "Polygon",
    kind: "evm",
    chainName: "matic-mainnet",
    nativeSymbol: "MATIC",
    decimals: 18,
    explorerUrl: "https://polygonscan.com/tx/",
    rpcUrls: ["https://polygon-rpc.com"],
    keywords: ["polygon", "matic", "polygonscan"],
  },
  {
    id: "arbitrum",
    label: "Arbitrum One",
    kind: "evm",
    chainName: "arbitrum-mainnet",
    nativeSymbol: "ETH",
    decimals: 18,
    explorerUrl: "https://arbiscan.io/tx/",
    rpcUrls: ["https://arb1.arbitrum.io/rpc"],
    keywords: ["arbitrum", "arbiscan", "arb"],
  },
  {
    id: "optimism",
    label: "Optimism",
    kind: "evm",
    chainName: "optimism-mainnet",
    nativeSymbol: "ETH",
    decimals: 18,
    explorerUrl: "https://optimistic.etherscan.io/tx/",
    rpcUrls: ["https://rpc.ankr.com/optimism", "https://mainnet.optimism.io"],
    keywords: ["optimism", "optimistic", "op mainnet", "optimistic etherscan"],
  },
  {
    id: "base",
    label: "Base",
    kind: "evm",
    chainName: "base-mainnet",
    nativeSymbol: "ETH",
    decimals: 18,
    explorerUrl: "https://basescan.org/tx/",
    rpcUrls: ["https://mainnet.base.org"],
    keywords: ["base", "basescan", "coinbase l2"],
  },
  {
    id: "avalanche",
    label: "Avalanche C-Chain",
    kind: "evm",
    chainName: "avalanche-mainnet",
    nativeSymbol: "AVAX",
    decimals: 18,
    explorerUrl: "https://snowtrace.io/tx/",
    rpcUrls: ["https://rpc.ankr.com/avalanche"],
    keywords: ["avalanche", "avax", "snowtrace"],
  },
  {
    id: "fantom",
    label: "Fantom",
    kind: "evm",
    chainName: "fantom-mainnet",
    nativeSymbol: "FTM",
    decimals: 18,
    explorerUrl: "https://ftmscan.com/tx/",
    rpcUrls: ["https://rpc.ankr.com/fantom"],
    keywords: ["fantom", "ftm", "ftmscan"],
  },
  {
    id: "gnosis",
    label: "Gnosis",
    kind: "evm",
    chainName: "gnosis-mainnet",
    nativeSymbol: "xDAI",
    decimals: 18,
    explorerUrl: "https://gnosisscan.io/tx/",
    rpcUrls: ["https://rpc.ankr.com/gnosis"],
    keywords: ["gnosis", "xdai", "gno"],
  },
];

export const NETWORKS = {
  evm: {
    id: "evm",
    label: "EVM-compatible chain",
    kind: "evm",
    nativeSymbol: "ETH",
    decimals: 18,
    explorerUrl: null,
    rpcUrls: [],
    keywords: [],
  },
  ethereum: EVM_CHAINS[0],
  bsc: EVM_CHAINS[1],
  polygon: EVM_CHAINS[2],
  arbitrum: EVM_CHAINS[3],
  optimism: EVM_CHAINS[4],
  base: EVM_CHAINS[5],
  avalanche: EVM_CHAINS[6],
  fantom: EVM_CHAINS[7],
  gnosis: EVM_CHAINS[8],
  solana: {
    id: "solana",
    label: "Solana",
    kind: "solana",
    nativeSymbol: "SOL",
    decimals: 9,
    explorerUrl: "https://solscan.io/tx/",
    rpcUrls: ["https://api.mainnet-beta.solana.com"],
    keywords: ["solana", "solscan", "spl", "serum", "raydium", "jupiter"],
  },
  bitcoin: {
    id: "bitcoin",
    label: "Bitcoin",
    kind: "bitcoin",
    nativeSymbol: "BTC",
    decimals: 8,
    explorerUrl: "https://blockchair.com/bitcoin/transaction/",
    rpcUrls: [],
    keywords: ["bitcoin", "btc", "txid", "utxo", "mempool", "blockchair"],
  },
  near: {
    id: "near",
    label: "NEAR Protocol",
    kind: "near",
    nativeSymbol: "NEAR",
    decimals: 24,
    explorerUrl: "https://nearblocks.io/txns/",
    rpcUrls: ["https://rpc.mainnet.near.org"],
    keywords: ["near", "nearblocks", "aurora"],
  },
};

export const EVM_CHAIN_LIST = EVM_CHAINS;